### ISSUE TITLE
how generate Address and how generate Wallet?

### ISSUE THREAD

**Issue by valentinc94** [madnesspie/django-obm#26]

**Comment by madnesspie** [comment]
You are welcome! There are two ways. Via ORM or REST API. 

You can just use django built-in ORM object manager:
```python
from cc_framework.blockchain import models

address=models.Address.objects.create(
    address="Your address",
    currency=currency_obj,
)
``` 

Or create post request on `/addresses` endpoint. But it requires the [configuration](https://django-cryptocurrency-framework.readthedocs.io/en/latest/installation.html#django).

Can you explain use case?

**Comment by madnesspie** [comment]
I will describe the question in the documentation.
